name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  shared_preferences: ^2.4.9
  file_picker: ^5.2.6
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env  # ✅ include env for Flutter Web

  plugin:
    platforms:
      linux:
        default_package: none
      macos:
        default_package: none
      windows:
        default_package: none
